### ISSUE TITLE
adding 2015 teams

### ISSUE THREAD

**Issue by 100ideas** [iGEM-QSF/iGEM-Team-Seeker#2]
I like team seeker. Did you write a script to pull out the abstracts? If so, can we run it again to grab the 2015 teams?

If not, let me know if you would accept a pull request for an updated `teams.json` file.

**Comment by Wing0** [comment]
Hey,
Good idea, thanks for bringing it up! We had a script to parse the team information but 2014 teams were only available as a PDF file from Jamboree (thanks to Waterloo 2015 for doing the work to put 2014 teams into it!). You can request for a pull and add 2015 teams, either by using the script or manually putting them there.

I'm going to look for the script if we still have it somewhere.

Best regards,
Oskari Vinko
Aalto-Helsinki 2014

**Comment by Wing0** [comment]
Hey,
We're going to ask Aalto-Helsinki 2016 to update the team seeker to 2015 teams :) As soon as we've assembled the team. So update coming in next 1-3 weeks.

-Oskari

**Comment by 100ideas** [comment]
awesome, thanks guys!

**Comment by Vaakapallo** [comment]
Actually, we do totally accept a pull request to the json-file too. Probably better to have it updated as soon as possible.

The old HTML-parser we used for the 2009-2013 data is not at all suitable for the 2015 format and I also seem to have misplaced it.

So, if someone can quickly get the info in the same JSON format that would be awesome. If not, the new team will figure it out in a while.
